name: Elixir CI

on: [push, pull_request_target]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      id: elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '23.0.2' # Define the OTP version [required]
    - name: Restore dependencies cache
      id: deps-cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile (warnings as errors)
      env:
        MIX_ENV: test
      run: mix compile --force --warnings-as-errors

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Check formatting
      run: mix format --check-formatted

  credo:
    name: Credo
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Credo
      run: mix credo --strict

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Run tests
      run: mix test --cover
    - name: Upload coverage artifact
      uses: zgosalvez/github-actions-report-lcov@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-files: ./coverage/lcov*.info
        artifact-name: elixir-code-coverage

  dialyzer:
    name: Dialzyer
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Restore Dialyzer cache
      id: dialyzer-cache
      uses: actions/cache@v2
      with:
        path: _build/dev/dialyxir*.plt*
        key: ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-${{ steps.elixir.elixir_version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-${{ steps.elixir.elixir_version }}-
          ${{ runner.os }}-dialyxir-${{ steps.elixir.otp-version }}-
    - name: Dialyzer
      run: mix dialyzer --halt-exit-status
