name: Elixir CI

on: [push, pull_request]

jobs:
  asdf:
    uses: paulswartz/mbta-workflows/.github/workflows/build-cache-asdf.yml@asdf-caching

  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: asdf

    steps:
    - uses: actions/checkout@v2
    - name: Restore ASDF cache
      uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: ${{ needs.asdf.outputs.cache-key }}
    - name: Reshim ASDF
      uses: mbta/actions/reshim-asdf@v1
    - name: Restore dependencies cache
      id: deps-cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: |
        mix local.rebar --foce
        mix local.hex --force
        mix deps.get
    - name: Compile (warnings as errors)
      run: mix compile --force --warnings-as-errors
    - name: Check formatting
      run: mix format --check-formatted
    - name: Credo
      run: mix credo --strict
    - name: Run tests
      run: mix test --cover
    - name: Save PR information
      run: |
        echo "${{ github.event.pull_request.number }}" > coverage/PR_NUMBER
        echo "${{ github.event.pull_request.head.sha }}" > coverage/PR_SHA
      if: github.event.pull_request
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: elixir-lcov
        path: coverage/
    - uses: mbta/actions/dialyzer@v1
